# .circleci/config.yml
version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 14.0.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
      - checkout
      - run:
          name: Build and Run Tests
          command: fastlane scan 
          environment:
            SCAN_SCHEME: CI
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan
workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test